name: Solar System Workflow

on:
  push:
    branches:
      - main
      - feature-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18,19,20]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm test
    - name: Build Docker Image
      run: docker build -t solar-system:latest .
    - name: Push Docker Image to DockerHub
      run: docker push solar-system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    # Install Ansible
    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    # Set up AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    # Run the Ansible playbook for deployment
    - name: Run Ansible Playbook to Deploy Application
      run: |
        ansible-playbook -i inventories/aws_ec2.yaml playbook-deploy.yaml
      env:
        MONGO_URI: 'mongodb+srv://${{ vars.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD }}@supercluster.d83jj.mongodb.net/superData'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Optional: Slack notification for deployment
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
