---
- hosts: tag__Name_Solar_System
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  tasks:
    - name: Install Docker
      ansible.builtin.apt: 
        name: docker
        state: present

    - name: Install Python
      ansible.builtin.package:
        name: python3
        state: present

    - name: Ensure the application is installed
      ansible.builtin.shell: |
        docker pull ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
        docker stop solar-system || true
        docker rm solar-system || true
        docker run -d --name solar-system -p 80:80 solar-system:${{ github.sha }}
      tags: deployment

    - name: Ensure application service is running
      ansible.builtin.systemd:
        name: docker
        state: started
