---
- hosts: tag__Name_Solar_System
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
  tasks:
    - name: Install Docker
      ansible.builtin.apt: 
        name: docker
        state: present
    - name: Install Python
      ansible.builtin.apt:
        name: python3
        state: present

    - name: Ensure the application is installed
      ansible.builtin.shell: |
        docker pull solar-system:latest
        docker stop solar-system || true
        docker rm solar-system || true
        docker run -d --name solar-system -p 80:80 solar-system:latest
      tags: deployment

    - name: Ensure application service is running
      ansible.builtin.systemd:
        name: docker
        state: started
